server:
  port: 8011

spring:
  application:
    name: payment-provider-hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning-sc?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    druid:
      max-active: 100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    # instance-id: payment-provider
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.darren.springcloud.entities
