server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1                     # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001            # 匹配提供的路由地址
          uri: lb://payment-provider
          predicates:                            # https://docs.spring.io/spring-cloud-gateway/docs/2.2.7.RELEASE/reference/html/#gateway-request-predicates-factories
            - Path=/payment/get/**               # 断言，路由相匹配的进行路由
            #- After=2021-02-27T00:00:00.000+08:00[Asia/Shanghai]
            #- Cookie=name, darren               # curl http://localhost:9527/payment/get/1 --cookie "name=darren"
            #- Header=X-Request-Id, \d+          # curl http://localhost:9527/payment/get/1 -H "X-Request-Id:123"

        - id: payment_routh2                     # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001            # 匹配提供的路由地址
          uri: lb://payment-provider
          predicates:
            - Path=/payment/discoveryClient      # 断言，路由相匹配的进行路由


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,
  instance:
    # instance-id: payment-provider
    prefer-ip-address: true