server:
  port: 8001

spring:
  application:
    name: payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning-sc?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    druid:
      max-active: 100

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.darren.springcloud.entities
